test_that("generate_dai assembles sections in the documented order", {
  config <- list(
    directory = "Output",
    path = list("C:/lib"),
    libraries = list("crop.dai"),
    horizons = list(list(name = "H1", texture_class = "FAO3")),
    columns = list(list(name = "C1", Soil = list(MaxRootingDepth = list(value = 100, unit = "cm"),
                                                  horizons = list(list(depth = -25, unit = "cm", horizon = "H1"))),
                        Movement = list(type = "vertical", zplus = -100))),
    crops = list(list(name = "Crop1", based_on = "default")),
    activities = list(list(name = "Act1", field_operations = list(list(plow = list())))),
    programs = list(list(name = "Prog1", type = "Daisy", weather = "none", column = "C1",
                          time = "2020-01-01", stop = "2020-12-31",
                          manager = list("Act1"), output = list("harvest"))),
    run = list("Prog1")
  )
  txt <- generate_dai(config)

  ## Every section present, in order.
  ordered_markers <- c('(directory "Output")', "(path ", "(input file", "(defhorizon",
                        "(defcolumn", "(defcrop", "(defaction", "(defprogram", '(run "Prog1")')
  positions <- vapply(ordered_markers, function(m) regexpr(m, txt, fixed = TRUE)[1], integer(1))
  expect_true(all(positions > 0))
  expect_true(all(diff(positions) > 0))
})

test_that("generate_dai writes consecutive (input file ...) lines without a blank line between them", {
  txt <- generate_dai(list(libraries = list("crop.dai", "tillage.dai", "log.dai")))
  expect_match(txt, '\\(input file "crop\\.dai"\\)\\n\\(input file "tillage\\.dai"\\)\\n\\(input file "log\\.dai"\\)')
  expect_false(grepl('(input file "crop.dai")\n\n(input file "tillage.dai")', txt, fixed = TRUE))
})

test_that("generate_dai omits absent sections entirely rather than emitting them empty", {
  txt <- generate_dai(list(activities = list(list(name = "A", field_operations = list(list(plow = list()))))))
  expect_false(grepl("defhorizon", txt))
  expect_false(grepl("defcolumn", txt))
  expect_false(grepl("defcrop", txt))
  expect_false(grepl("defprogram", txt))
  expect_match(txt, "defaction")
})

test_that("generate_dai's `activities` also accepts a bare single-activity config (back-compat)", {
  txt <- generate_dai(list(name = "Solo", field_operations = list(list(plow = list()))))
  expect_match(txt, '\\(defaction "Solo" activity')
})

test_that("generate_dai writes to output_path when given", {
  tmp <- tempfile(fileext = ".dai")
  on.exit(unlink(tmp))
  txt <- generate_dai(list(run = list("X")), output_path = tmp)
  expect_true(file.exists(tmp))
  expect_equal(paste(readLines(tmp), collapse = "\n"), txt)
})

test_that("generate_dai includes a file-level comment as ;; header lines", {
  txt <- generate_dai(list(comment = "line one\nline two", run = list("X")))
  expect_match(txt, ";; line one")
  expect_match(txt, ";; line two")
  expect_match(txt, ";; line one\n;; line two")
  expect_false(grepl(";; line one\n\n;; line two", txt, fixed = TRUE))
})

test_that("yaml_to_dai reads a YAML file and produces the same text as generate_dai on its parsed content", {
  path <- test_path("fixtures", "dai_yaml", "sbarley-management.yaml")
  txt <- yaml_to_dai(path)
  expect_match(txt, 'defaction "SBarley w\\. MF"')
  expect_match(txt, 'defaction "SBarley w\\. OF"')
  expect_match(txt, "Generated by generate_dai\\(\\) from sbarley-management\\.yaml")
})

test_that("yaml_to_dai errors clearly on a missing file", {
  expect_error(yaml_to_dai("does-not-exist.yaml"), "not found")
})

test_that("yaml_to_dai handles a top-level description and a scalar (library-sourced) manager", {
  tmp <- tempfile(fileext = ".yaml")
  on.exit(unlink(tmp))
  yaml::write_yaml(list(
    description = "Demonstrate automatic parameter calibration.",
    programs = list(list(name = "MySim", type = "Daisy", manager = "SBarley w. MF")),
    run = list("MySim")
  ), tmp)

  txt <- yaml_to_dai(tmp)
  expect_match(txt, '\\(description "Demonstrate automatic parameter calibration\\."\\)')
  expect_match(txt, '\\(manager "SBarley w\\. MF"\\)')
  expect_false(grepl("manager activity", txt))

  ## Round-trips through parse_dai()/generate_dai() too, since
  ## yaml_to_dai() has no field-specific logic of its own -- it just reads
  ## YAML into a list and hands it to generate_dai().
  expect_equal(generate_dai(parse_dai(txt)), txt)
})

test_that("yaml_to_dai reproduces the confirmed-against-real-Daisy sbarley/cauliflower syntax", {
  sbarley <- yaml_to_dai(test_path("fixtures", "dai_yaml", "sbarley-management.yaml"))
  expect_match(sbarley, '\\(fertilize \\("N25S" \\(weight 115 \\[kg N/ha\\]\\)\\)\\)')
  expect_match(sbarley, '\\(fertilize \\("pig_slurry" \\(volatilization 5 \\[%\\]\\) \\(weight 28 \\[T w\\.w\\./ha\\]\\)\\) \\(to -1 \\[cm\\]\\)\\)')

  cauliflower <- yaml_to_dai(test_path("fixtures", "dai_yaml", "cauliflower-management.yaml"))
  expect_match(cauliflower, "\\(while \\(wait_mm_dd 6 15\\)")
  expect_match(cauliflower, '\\(repeat "irrigation"\\)')
})

test_that("yaml_to_dai reproduces the confirmed-against-real-Daisy west-soil-column scenario", {
  txt <- yaml_to_dai(test_path("fixtures", "dai_yaml", "west-soil-column.yaml"))
  expect_match(txt, 'defhorizon "Hor_25" FAO3')
  expect_match(txt, 'defcolumn "Soil_Column" default')
  expect_match(txt, 'defcrop "Grass Scotland" "Grass to grain"')
  expect_match(txt, 'defaction "Grass for cutting" activity\\s*\\n\\s*"Sowing Grass"\\s*\\n\\s*"Grass - cuts"')
  expect_match(txt, 'defprogram "west" "Common"')
  expect_match(txt, '\\(run "west"\\)')
})
