## dai_read.R -- Read a Daisy `.dai` file back into the same nested-list
## config shape generate_dai() consumes, so it can be read, edited in R,
## and regenerated. This is the inverse of dai_generate.R's top-level
## assembly, and depends on every per-domain parse_*() function (
## parse_horizon() in dai_horizons.R, parse_column() in dai_columns.R,
## parse_crop() in dai_crops.R, parse_activity() in dai_management.R,
## parse_program() in dai_programs.R) plus the shared tokenizer/generic
## inversion mechanism in dai_parse_helpers.R.
##
## ---------------------------------------------------------------------
## Scope -- read dai_parse_helpers.R's header first
## ---------------------------------------------------------------------
## This reads exactly what generate_dai() can produce -- directory/path/
## library includes, defhorizon, defcolumn, defcrop, defaction,
## defprogram, and standalone run statements -- not arbitrary Daisy
## syntax. A top-level construct outside that (deflog, defchemical, or
## anything else this project has no renderer for) raises a clear error
## naming what wasn't recognized, rather than guessing or dropping it.
##
## Two public entry points, mirroring generate_dai()/yaml_to_dai() --
## parse_dai() is the pure, text-in/list-out worker (like generate_dai()
## is the pure list-in/text-out worker); read_dai() is the file-reading
## convenience wrapper around it (like yaml_to_dai() is the YAML-file-
## reading wrapper around generate_dai()):
##   parse_dai(text)                        text -> config list (pure)
##   read_dai(dai_path, yaml_path = NULL)   reads a file, calls parse_dai(),
##                                           optionally writes the config
##                                           back out as YAML too
##
## ---------------------------------------------------------------------
## A representational note (see dai_parse_helpers.R / dai_management.R
## for the full reasoning): several places in this schema let the same
## `.dai` text arise from more than one YAML structuring (a comment
## attached to an operation's own fields vs. a standalone comment entry
## right before it; `date` on an operation vs. a standalone `wait` entry;
## a `manager` repeat shorthand vs. the name written out N times; a
## weather/fertilise unit/method left to its default vs. set explicitly).
## Parsing always picks the simpler, more explicit reconstruction. It is
## not guaranteed to recover the *exact* YAML a human originally wrote --
## it is guaranteed that regenerating from what it *does* recover
## (`generate_dai(read_dai(path))`) reproduces the same `.dai` text.
## That's this feature's actual goal: read a file, edit it in R, and
## regenerate it -- not perfectly reconstruct the original authoring
## choices.
## ---------------------------------------------------------------------

## -- public entry points -----------------------------------------------------

#' Parse Daisy `.dai` text into the config list `generate_dai()` consumes
#'
#' The inverse of `generate_dai()`, bounded to exactly the same schema (see
#' this file's scope note and dai_parse_helpers.R's). Comments (`;;` lines,
#' and `;` end-of-line notes) are recovered wherever `generate_dai()` can
#' put one: a file-level `comment`, a block's own `comment`,
#' `field_comments` inside a block, a comment on a library or `run` entry,
#' and `trailing_comment` at the end of the file. `;;;` lines that are
#' `generate_dai()`'s own header are discarded, except that a
#' `;;; Generated by generate_dai() from <file>` line (if present) is read
#' back into `config$source_file`, matching what `generate_dai()` writes
#' there from `yaml_to_dai()`. Other `;;;` banners are kept as comments.
#'
#' This is the pure, text-in/list-out worker -- the counterpart to
#' `generate_dai()`'s pure list-in/text-out. To parse a `.dai` *file*
#' instead of text you already have in hand, use `read_dai()`, the
#' file-reading wrapper around this function (matching how `yaml_to_dai()`
#' is the YAML-file-reading wrapper around `generate_dai()`).
#'
#' @param text Character scalar: the full text of a `.dai` file.
#'
#' @return A list in the schema documented at the top of dai_generate.R --
#'   suitable to pass straight to `generate_dai()`.
#'
#' @details
#' Unrecognized top-level Daisy (`deflog`, `defchemical`, ...) is kept as
#' `daisy_script` entries (original source text) and written back as-is by
#' `generate_dai()`. Unrecognized fields inside a `defprogram` (e.g.
#' `print_time`) are kept the same way on that program. If a *recognized*
#' construct is malformed (a `defhorizon` with no texture class, an
#' unterminated `(`, ...), `parse_dai()` keeps going and collects every
#' such problem across the whole file before raising a single error
#' listing them all -- one line each, in file order, naming the source
#' line number it starts on.
#'
#' @examples
#' \dontrun{
#' config <- parse_dai(readLines("west.dai", warn = FALSE) |> paste(collapse = "\n"))
#' config$programs[[1]]$log_prefix <- "revised_"
#' cat(generate_dai(config))
#' }
#' @export
parse_dai <- function(text) {
  ## A file *path* passed here by mistake (parse_dai() takes .dai text --
  ## read_dai() does the file reading) would otherwise tokenize as one
  ## bare atom with no recognizable construct, surfacing as a confusing
  ## "construct #1 (atom): unrecognized top-level construct". Catch the
  ## common case directly and point at the right function instead.
  if (length(text) == 1 && !grepl("[()]", text, fixed = FALSE) && file.exists(text))
    stop("parse_dai() expects the *text* of a .dai file, not a file path -- did you mean ",
         "read_dai(\"", text, "\") instead?")

  nodes <- .dai_parse_tree(.dai_tokenize(text))
  n <- length(nodes)
  cfg <- list()
  problems <- character(0)
  text_lines <- strsplit(text, "\n", fixed = TRUE)[[1]]
  last_section <- "header"

  src_lines <- grep("^;;; Generated by generate_dai\\(\\) from .+ -- edits will be lost",
                     text_lines, value = TRUE)
  if (length(src_lines) >= 1)
    cfg$source_file <- sub("^;;; Generated by generate_dai\\(\\) from (.+) -- edits will be lost.*$",
                            "\\1", src_lines[1])

  i <- 1L
  ## A leading comment run, if it's the very first thing in the file, is
  ## the file-level `comment:` field -- deterministic even though it's the
  ## same textual position a first block's own comment would occupy,
  ## since regenerating from either interpretation produces identical
  ## output (see this file's representational note).
  if (n >= 1 && nodes[[1]]$kind == "comment") {
    j <- 1L
    while (j <= n && nodes[[j]]$kind == "comment") j <- j + 1L
    cfg$comment <- paste(vapply(nodes[1:(j - 1L)], `[[`, character(1), "text"), collapse = "\n")
    i <- j
  }

  construct_num <- 0L
  while (i <= n) {
    nd <- nodes[[i]]
    if (nd$kind == "comment") {
      j <- i
      while (j <= n && nodes[[j]]$kind == "comment") j <- j + 1L
      if (j > n) {
        cfg$trailing_comment <- paste(vapply(nodes[i:(j - 1L)], `[[`, character(1), "text"),
                                      collapse = "\n")
        break
      }
      comment_text <- paste(vapply(nodes[i:(j - 1L)], `[[`, character(1), "text"), collapse = "\n")
      construct <- nodes[[j]]
      i <- j
    } else {
      comment_text <- NULL
      construct <- nd
    }

    construct_num <- construct_num + 1L
    label <- if (construct$kind == "list" && length(construct$children) >= 1 &&
                 construct$children[[1]]$kind == "atom")
      construct$children[[1]]$text
    else
      construct$kind

    tryCatch({
      if (construct$kind != "list" || length(construct$children) < 1 || construct$children[[1]]$kind != "atom")
        stop("dai parse error: unrecognized top-level construct")
      head <- construct$children[[1]]$text
      body <- construct$children[-1]

      if (identical(head, "description")) {
        if (length(body) != 1 || !(body[[1]]$kind %in% c("atom", "string")))
          stop("dai parse error: unrecognized (description ...) form")
        if (!is.null(comment_text)) cfg$section_comments$description <- comment_text
        cfg$description <- body[[1]]$text
        last_section <- "top"

      } else if (identical(head, "directory")) {
        if (length(body) != 1 || body[[1]]$kind != "string")
          stop("dai parse error: unrecognized (directory ...) form")
        if (!is.null(comment_text)) cfg$section_comments$directory <- comment_text
        cfg$directory <- body[[1]]$text
        last_section <- "top"

      } else if (identical(head, "path")) {
        if (!is.null(comment_text)) cfg$section_comments$path <- comment_text
        cfg$path <- vapply(body, function(nd2) nd2$text, character(1))
        last_section <- "top"

      } else if (identical(head, "input")) {
        if (length(body) != 2 || body[[1]]$kind != "atom" || !identical(body[[1]]$text, "file") ||
            body[[2]]$kind != "string")
          stop("dai parse error: unrecognized (input ...) form")
        lib <- if (is.null(comment_text)) body[[2]]$text else list(file = body[[2]]$text, comment = comment_text)
        cfg$libraries <- c(cfg$libraries, list(lib))
        last_section <- "libraries"

      } else if (identical(head, "defhorizon")) {
        entry <- parse_horizon(body)
        if (!is.null(comment_text)) entry$comment <- comment_text
        cfg$horizons <- c(cfg$horizons, list(entry))
        last_section <- "horizons"

      } else if (identical(head, "defcolumn")) {
        entry <- parse_column(body)
        if (!is.null(comment_text)) entry$comment <- comment_text
        cfg$columns <- c(cfg$columns, list(entry))
        last_section <- "columns"

      } else if (identical(head, "defcrop")) {
        entry <- parse_crop(body)
        if (!is.null(comment_text)) entry$comment <- comment_text
        cfg$crops <- c(cfg$crops, list(entry))
        last_section <- "crops"

      } else if (identical(head, "defaction")) {
        entry <- parse_activity(body)
        if (!is.null(comment_text)) entry$comment <- comment_text
        cfg$activities <- c(cfg$activities, list(entry))
        last_section <- "activities"

      } else if (identical(head, "defprogram")) {
        entry <- parse_program(body)
        if (!is.null(comment_text)) entry$comment <- comment_text
        cfg$programs <- c(cfg$programs, list(entry))
        last_section <- "programs"

      } else if (identical(head, "run")) {
        if (length(body) != 1 || !(body[[1]]$kind %in% c("atom", "string")))
          stop("dai parse error: unrecognized (run ...) form")
        run <- if (is.null(comment_text)) body[[1]]$text else list(name = body[[1]]$text, comment = comment_text)
        cfg$run <- c(cfg$run, list(run))
        last_section <- "run"

      } else {
        ## Unrecognized top-level Daisy (deflog, defchemical, ...) -- keep
        ## the original source text and write it back as-is.
        entry <- list(raw = .dai_source_slice(text_lines, construct), after = last_section)
        if (!is.null(comment_text)) entry$comment <- comment_text
        cfg$daisy_script <- c(cfg$daisy_script, list(entry))
      }
    }, error = function(e) {
      problems <<- c(problems, sprintf("- line %s, construct #%d (%s): %s",
                                        construct$line %||% "?", construct_num, label, conditionMessage(e)))
    })
    i <- i + 1L
  }

  if (length(problems) > 0)
    stop("dai parse error: found ", length(problems), " problem(s) reading this file -- ",
         "outside generate_dai()'s bounded schema (see dai_parse_helpers.R's scope note):\n",
         paste(problems, collapse = "\n"))

  cfg
}

#' Read a Daisy `.dai` file into the config list `generate_dai()` consumes
#'
#' Reads `dai_path`, parses it with `parse_dai()`, and returns the config
#' list -- so a file can be read, edited in R, and regenerated:
#' `generate_dai(read_dai("west.dai"))` reproduces it. Pass `yaml_path` to
#' also write the parsed config out as a YAML file, e.g. to hand-edit from
#' there instead, or to check what `read_dai()` recovered.
#'
#' @param dai_path Character scalar. Path to the input `.dai` file.
#' @param yaml_path Character scalar, or `NULL` (default). If given, the
#'   parsed config is also written to this path as YAML (via
#'   `yaml::write_yaml()`).
#'
#' @return The parsed config list (see `parse_dai()`).
#'
#' @examples
#' \dontrun{
#' config <- read_dai("west.dai")
#' config$programs[[1]]$log_prefix <- "revised_"
#' generate_dai(config, output_path = "west_revised.dai")
#'
#' ## Or just convert an existing .dai file to YAML, to edit by hand:
#' read_dai("west.dai", yaml_path = "west.yaml")
#' }
#' @export
read_dai <- function(dai_path, yaml_path = NULL) {
  if (!file.exists(dai_path)) stop("File not found: ", dai_path)
  text <- paste(readLines(dai_path, warn = FALSE), collapse = "\n")
  config <- parse_dai(text)

  if (!is.null(yaml_path)) {
    yaml::write_yaml(config, yaml_path)
    message("Wrote ", yaml_path)
  }
  config
}

## dai_read.R ends here.
