## dai_parse_helpers.R -- the inverse of dai_helpers.R's generic mechanism:
## turn Daisy .dai text back into the same nested-list config shape
## generate_dai() consumes, so a file can be read, edited in R, and
## regenerated.
##
## ---------------------------------------------------------------------
## Scope -- deliberately bounded
## ---------------------------------------------------------------------
## This is NOT a general Daisy/.dai parser. Real .dai files can contain
## constructs this project has never built a renderer for (deflog,
## defchemical, crop-physiology submodels beyond Devel/Partit, and so on)
## -- parsing arbitrary Daisy syntax is a much bigger undertaking than
## what's needed here. Instead, this file (and its per-domain
## counterparts -- parse_horizon() in dai_horizons.R, parse_column() in
## dai_columns.R, parse_crop() in dai_crops.R, parse_activity() in
## dai_management.R, parse_program() in dai_programs.R, and parse_dai() /
## read_dai() in dai_read.R) is the mechanical *inverse* of exactly what
## generate_dai() can produce -- the same bounded schema, walked
## backwards. A file outside that bounded grammar will raise a clear
## error rather than silently mis-parsing or dropping content.
##
## ---------------------------------------------------------------------
## Tokenizer
## ---------------------------------------------------------------------
## Daisy's syntax here is Lisp-like s-expressions plus one addition:
## `[unit]` immediately after a value. Six token types:
##   lparen / rparen   "(" / ")"
##   string             a "quoted string", backslash-escaped
##   bracket            the raw text between `[` and `]` (may be empty)
##   atom               a bare token (number, `true`/`false`, or a bare
##                       keyword like `Cosby_et_al`, `default`, `vertical`)
##   comment             text of a `;;` (content) comment line
##   meta_comment        text of a `;;;` (generator-metadata) comment line
##                       -- always discarded; see .dai_parse_tree()
## ---------------------------------------------------------------------

## -- tokenizer -----------------------------------------------------------

#' @keywords internal
.dai_tokenize <- function(text) {
  n <- nchar(text)
  i <- 1L
  toks <- vector("list", 0L)

  ## Line numbers, for error messages -- computed once up front (rather
  ## than an incremental running counter) so `push()` can just look up
  ## the line of any character position, including positions already
  ## behind the cursor (e.g. a string/comment's *start*, not its end).
  nl_pos <- gregexpr("\n", text, fixed = TRUE)[[1]]
  if (identical(nl_pos, -1L)) nl_pos <- integer(0)
  line_at <- function(pos) findInterval(pos - 1L, nl_pos) + 1L

  push <- function(type, value, at) toks[[length(toks) + 1L]] <<- list(type = type, value = value, line = line_at(at))

  while (i <= n) {
    ch <- substr(text, i, i)
    if (ch %in% c(" ", "\t", "\r", "\n")) { i <- i + 1L; next }

    if (ch == ";") {
      j <- i
      while (j <= n && substr(text, j, j) == ";") j <- j + 1L
      nsemi <- j - i
      rest <- substr(text, j, n)
      eol <- regexpr("\n", rest, fixed = TRUE)
      line_end <- if (eol == -1L) n else (j + eol - 2L)
      raw <- substr(text, j, line_end)
      raw <- sub("^ ", "", raw)  ## render_comment_lines() emits ";; text" -- one leading space
      ## Only generate_dai()'s own ;;; header lines are metadata (dropped).
      ## Other ;;; banners (e.g. ";;; file ends here") are kept as comments.
      is_gen_meta <- nsemi >= 3L && grepl("^(Generated by generate_dai\\(\\)|Generated:)", raw)
      push(if (is_gen_meta) "meta_comment" else "comment", raw, i)
      i <- line_end + 1L
      next
    }

    if (ch == "(") { push("lparen", NULL, i); i <- i + 1L; next }
    if (ch == ")") { push("rparen", NULL, i); i <- i + 1L; next }

    if (ch == "[") {
      rest <- substr(text, i + 1L, n)
      close <- regexpr("]", rest, fixed = TRUE)
      if (close == -1L)
        stop("dai parse error: unterminated [ ] unit bracket at line ", line_at(i), " (position ", i, ")")
      raw <- substr(text, i + 1L, i + close - 1L)
      push("bracket", raw, i)
      i <- i + close + 1L
      next
    }

    if (ch == '"') {
      start <- i
      j <- i + 1L
      buf <- character(0)
      repeat {
        if (j > n)
          stop("dai parse error: unterminated string starting at line ", line_at(start), " (position ", start, ")")
        c2 <- substr(text, j, j)
        if (c2 == "\\") { buf <- c(buf, substr(text, j + 1L, j + 1L)); j <- j + 2L; next }
        if (c2 == '"') break
        buf <- c(buf, c2); j <- j + 1L
      }
      push("string", paste(buf, collapse = ""), start)
      i <- j + 1L
      next
    }

    j <- i
    while (j <= n && !(substr(text, j, j) %in% c(" ", "\t", "\r", "\n", "(", ")", "[", "]", '"', ";"))) {
      j <- j + 1L
    }
    if (j == i)
      stop("dai parse error: unexpected character '", ch, "' at line ", line_at(i), " (position ", i, ")")
    push("atom", substr(text, i, j - 1L), i)
    i <- j
  }
  toks
}

## -- raw tree ------------------------------------------------------------
##
## Turns the flat token stream into a tree of nodes:
##   list(kind = "atom",    text = ..., line = ...)
##   list(kind = "string",  text = ..., line = ...)
##   list(kind = "bracket", text = ..., line = ...)
##   list(kind = "comment", text = ..., line = ...)   -- a ";;" content
##                             comment, kept in sequence among its siblings
##   list(kind = "list", children = list(...), line = ...)  -- a
##                             parenthesized form; `line` is its opening
##                             `(`'s line
## Every node's `line` is the source line it starts on (1-based),
## letting parse errors point at exactly where the problem is in the
## original file -- see dai_read.R's parse_dai(). `meta_comment` tokens
## (";;;" generator lines) are dropped here and never become nodes --
## they carry no data this schema round-trips.

#' @keywords internal
.dai_parse_tree <- function(tokens) {
  n <- length(tokens)
  pos <- 1L

  parse_seq <- function(stop_on_rparen) {
    nodes <- vector("list", 0L)
    while (pos <= n) {
      tok <- tokens[[pos]]
      if (tok$type == "rparen") {
        if (stop_on_rparen) return(nodes)
        stop("dai parse error: unexpected ')' at line ", tok$line)
      }
      if (tok$type == "meta_comment") { pos <<- pos + 1L; next }
      if (tok$type == "comment") {
        nodes[[length(nodes) + 1L]] <- list(kind = "comment", text = tok$value, line = tok$line)
        pos <<- pos + 1L
        next
      }
      if (tok$type == "lparen") {
        open_line <- tok$line
        pos <<- pos + 1L
        children <- parse_seq(TRUE)
        if (pos > n || tokens[[pos]]$type != "rparen")
          stop("dai parse error: unterminated '(' opened at line ", open_line)
        pos <<- pos + 1L
        nodes[[length(nodes) + 1L]] <- list(kind = "list", children = children,
                                            line = open_line, end_line = tokens[[pos - 1L]]$line)
        next
      }
      if (tok$type %in% c("bracket", "string", "atom")) {
        nodes[[length(nodes) + 1L]] <- list(kind = tok$type, text = tok$value, line = tok$line)
        pos <<- pos + 1L
        next
      }
      stop("dai parse error: unexpected token type '", tok$type, "'")
    }
    if (stop_on_rparen) stop("dai parse error: unterminated '(' -- ran out of input")
    nodes
  }

  parse_seq(FALSE)
}

#' Parse Daisy `.dai` text into the raw node tree (tokenize + nest parens).
#' Exposed mainly for testing; per-domain parsers work from this tree.
#' @keywords internal
.dai_parse_raw <- function(text) .dai_parse_tree(.dai_tokenize(text))

## -- scalar / generic-value inversion -------------------------------------
## The exact inverse of render_generic_value() / render_generic_block_body()
## (dai_helpers.R): given the *remaining* sibling nodes of a `(key ...)`
## form (i.e. everything after the leading key atom), reconstruct whichever
## R value would have rendered to that shape.

#' @keywords internal
.dai_looks_numeric <- function(text) {
  grepl("^-?[0-9]+(\\.[0-9]+)?$", text)
}

#' @keywords internal
.dai_scalar_node_value <- function(node) {
  if (node$kind == "string") return(node$text)
  if (node$kind == "atom") {
    if (identical(node$text, "true")) return(TRUE)
    if (identical(node$text, "false")) return(FALSE)
    if (.dai_looks_numeric(node$text)) return(as.numeric(node$text))
    return(node$text)
  }
  stop("dai parse error: expected a scalar (atom or string) node, got kind '", node$kind, "'")
}

#' @keywords internal
.dai_is_field_form <- function(node) {
  node$kind == "list" && length(node$children) >= 1L && node$children[[1]]$kind == "atom"
}

#' @keywords internal
.dai_is_plf_point <- function(node) {
  node$kind == "list" && length(node$children) == 2L &&
    all(vapply(node$children, function(c2) c2$kind == "atom" && .dai_looks_numeric(c2$text), logical(1)))
}

#' Parse one `(key ...)` form into `list(key = ..., value = ...)`.
#' @keywords internal
.dai_parse_field_form <- function(node) {
  stopifnot(node$kind == "list", length(node$children) >= 1L, node$children[[1]]$kind == "atom")
  key <- node$children[[1]]$text
  rest <- node$children[-1]
  list(key = key, value = .dai_parse_generic_rest(rest))
}

#' Reconstruct the R value that would render (via render_generic_value())
#' to the given `rest` nodes (everything after a field's leading key atom).
#' @keywords internal
.dai_parse_generic_rest <- function(rest) {
  n <- length(rest)

  ## bare scalar: (key value) -- number, bool, or a bare/quoted keyword
  if (n == 1L && rest[[1]]$kind %in% c("atom", "string")) {
    return(.dai_scalar_node_value(rest[[1]]))
  }

  ## value/unit pair: (key value [unit])
  if (n == 2L && rest[[1]]$kind %in% c("atom", "string") && rest[[2]]$kind == "bracket") {
    return(list(value = .dai_scalar_node_value(rest[[1]]), unit = rest[[2]]$text))
  }

  ## PLF table: (key (x1 y1)(x2 y2)...) -- every remaining sibling is a
  ## 2-numeric-atom parenthesized point. Checked before the method-pair /
  ## nested-dict cases below since a PLF point is also technically a
  ## "list" node but never has a leading non-numeric key atom.
  if (n >= 1L && all(vapply(rest, .dai_is_plf_point, logical(1)))) {
    return(lapply(rest, function(pt)
      as.numeric(vapply(pt$children, function(c2) c2$text, character(1)))))
  }

  ## method pair: (key method (f1 v1)(f2 v2)...) -- a leading bare symbol
  ## followed by one or more `(field value)` forms.
  if (n >= 2L && rest[[1]]$kind == "atom" &&
      all(vapply(rest[-1], .dai_is_field_form, logical(1)))) {
    inner_fields <- lapply(rest[-1], .dai_parse_field_form)
    inner <- setNames(lapply(inner_fields, `[[`, "value"),
                       vapply(inner_fields, `[[`, character(1), "key"))
    return(list(rest[[1]]$text, inner))
  }

  ## nested dict, no leading method keyword: (key (f1 v1)(f2 v2)...)
  if (n >= 1L && all(vapply(rest, .dai_is_field_form, logical(1)))) {
    fields <- lapply(rest, .dai_parse_field_form)
    return(setNames(lapply(fields, `[[`, "value"),
                     vapply(fields, `[[`, character(1), "key")))
  }

  stop("dai parse error: unrecognized field-value shape (", n, " sibling node(s))")
}

.dai_without_comments <- function(nodes) {
  Filter(function(nd) nd$kind != "comment", nodes)
}

.dai_join_comment_text <- function(nodes) {
  paste(vapply(nodes, `[[`, character(1), "text"), collapse = "\n")
}

.dai_merge_comment <- function(existing, new) {
  if (is.null(new) || !nzchar(new)) return(existing)
  if (is.null(existing) || !nzchar(existing)) return(new)
  paste(existing, new, sep = "\n")
}

#' Group sibling nodes into commented items. A `;;`/`;` run immediately
#' before a construct becomes that item's `comment`; a comment on the same
#' source line as the previous construct (an end-of-line `; ...`) is folded
#' into that previous item's comment. A trailing run with no following
#' construct is returned as `trailing`.
.dai_split_commented_items <- function(nodes) {
  items <- list()
  pending <- NULL
  i <- 1L
  n <- length(nodes)
  while (i <= n) {
    if (nodes[[i]]$kind == "comment") {
      j <- i
      while (j <= n && nodes[[j]]$kind == "comment") j <- j + 1L
      text <- .dai_join_comment_text(nodes[i:(j - 1L)])
      same_line_as_prev <- length(items) > 0 &&
        identical(nodes[[i]]$line, items[[length(items)]]$node$line)
      if (same_line_as_prev) {
        prev <- items[[length(items)]]
        prev$comment <- .dai_merge_comment(prev$comment, text)
        items[[length(items)]] <- prev
      } else {
        pending <- .dai_merge_comment(pending, text)
      }
      i <- j
    } else {
      items[[length(items) + 1L]] <- list(comment = pending, node = nodes[[i]])
      pending <- NULL
      i <- i + 1L
    }
  }
  list(items = items, trailing = pending)
}

.dai_set_field_comment <- function(field_comments, key, text) {
  if (is.null(text) || !nzchar(text)) return(field_comments)
  field_comments[[key]] <- .dai_merge_comment(field_comments[[key]], text)
  field_comments
}

#' Parse every `(key ...)` sibling of a block body into a named list -- the
#' inverse of `render_generic_block_body()`. Every sibling must be a
#' `(key ...)` field form. A `;;`/`;` comment interleaved between fields
#' (or at the end of a field's own line) is recovered on `field_comments`
#' keyed by the field it precedes (or, for an end-of-line comment, the
#' field it shares a line with), and regenerated immediately before that
#' field. Any other unexpected node raises a clear error rather than being
#' silently skipped, per this file's scope note.
#' @keywords internal
.dai_parse_generic_block_body <- function(nodes) {
  split <- .dai_split_commented_items(nodes)
  items <- split$items
  if (length(items) == 0) {
    out <- setNames(list(), character(0))
    if (!is.null(split$trailing)) out$field_comments <- list(.trailing = split$trailing)
    return(out)
  }
  bad <- Filter(function(it) !.dai_is_field_form(it$node), items)
  if (length(bad) > 0)
    stop("dai parse error: expected only (key value) fields in this block body, found a '",
         bad[[1]]$node$kind, "' node -- outside generate_dai()'s bounded schema")
  fields <- lapply(items, function(it) .dai_parse_field_form(it$node))
  out <- setNames(lapply(fields, `[[`, "value"),
                  vapply(fields, `[[`, character(1), "key"))
  field_comments <- list()
  for (i in seq_along(items)) {
    field_comments <- .dai_set_field_comment(field_comments, fields[[i]]$key, items[[i]]$comment)
  }
  if (!is.null(split$trailing))
    field_comments <- .dai_set_field_comment(field_comments, ".trailing", split$trailing)
  if (length(field_comments) > 0) out$field_comments <- field_comments
  out
}

## -- comment attachment ----------------------------------------------------
##
## `with_comment()` (dai_helpers.R) always emits a block's `comment:` field
## as ";;" line(s) immediately *before* that block's own opening line. So:
## if the node immediately preceding a top-level construct in its sibling
## list is a `comment` node (or a run of them), that's the construct's
## `comment` field -- join multi-line comments back with "\n", matching
## how `render_comment_lines()` split them.

#' Given a sibling-node list and the index of a construct's own node,
#' collect any immediately-preceding `comment` nodes as a single string
#' (or NULL if none), and return the number of nodes consumed.
#' @keywords internal
.dai_leading_comment <- function(nodes, idx) {
  j <- idx - 1L
  lines <- character(0)
  while (j >= 1L && nodes[[j]]$kind == "comment") { lines <- c(nodes[[j]]$text, lines); j <- j - 1L }
  if (length(lines) == 0) return(list(comment = NULL, consumed = 0L))
  list(comment = paste(lines, collapse = "\n"), consumed = idx - 1L - j)
}

## -- bare-name / positional-description inversion --------------------------
##
## `.q()` always quotes on the render side (see its own doc comment), but
## real hand-written `.dai` files commonly use bare (unquoted) symbols for
## any name that has no spaces (`Ap`, `Andeby`, `MySim`, ...) -- valid
## Daisy syntax this project's own renderers just never happen to produce.
## Parsing accepts either. Likewise, Daisy's model-definition forms
## (`defhorizon`/`defcolumn`/`defcrop`/`defprogram`) accept an optional
## descriptive string positioned right after their name/parent-or-type
## arguments, equivalent to an explicit `(description "...")` field --
## this project's renderers always emit `description` as that explicit
## field instead, so parsing folds the positional form into the same
## `cfg$description`.

#' Parse a name/reference node that Daisy also accepts as a bare symbol
#' (not just a quoted string).
#' @keywords internal
.dai_parse_name_node <- function(node) {
  if (node$kind %in% c("atom", "string")) return(node$text)
  stop("dai parse error: expected a name (bare symbol or quoted string), got kind '", node$kind, "'")
}

#' If the next sibling node is a bare/quoted string (not a `(key value)`
#' field form), consume it as a positional `description`. Returns
#' `list(description = ..., rest = ...)` -- `description` is `NULL` (and
#' `rest` is `children` unchanged) when the next node isn't a string.
#' @keywords internal
.dai_consume_positional_description <- function(children) {
  if (length(children) >= 1 && children[[1]]$kind == "string")
    return(list(description = children[[1]]$text, rest = children[-1]))
  list(description = NULL, rest = children)
}

## -- parent-ref inversion --------------------------------------------------
## Inverse of .render_parent_ref(): a bare `default` atom means "no
## based_on" (config field simply omitted); anything else is a quoted
## reference, taken verbatim.
#' @keywords internal
.dai_parse_parent_ref <- function(node) {
  if (node$kind == "atom" && identical(node$text, "default")) return(NULL)
  if (node$kind %in% c("atom", "string")) return(node$text)
  stop("dai parse error: expected a parent-reference atom/string")
}

## -- generic fallback: reconstruct Daisy text from a node -----------------
##
## Used only for the schema's own explicit escape hatches (`raw:` on a
## field_operation, or a `date`/`condition` this project's mini-language
## doesn't have a shorthand for) -- never as a substitute for a "real"
## parse elsewhere. Doesn't reproduce the *original* whitespace, only
## semantically equivalent text (Daisy is whitespace-insensitive here,
## and since the value round-trips right back through this same escape
## hatch, that's all regenerating the file needs).

#' Original source lines covered by a list node (opening `(` through its
#' matching `)`), falling back to `.dai_unparse_node()` if line bounds are
#' missing. Used to round-trip unrecognized Daisy as `daisy_script`.
.dai_source_slice <- function(text_lines, node) {
  start <- node$line
  end <- node$end_line %||% node$line
  if (is.null(start) || is.null(text_lines) || start < 1L || end > length(text_lines) || end < start)
    return(.dai_unparse_node(node))
  paste(text_lines[start:end], collapse = "\n")
}

#' @keywords internal
.dai_unparse_node <- function(node) {
  if (node$kind == "atom") return(node$text)
  if (node$kind == "string") return(.q(node$text))
  if (node$kind == "bracket") return(sprintf("[%s]", node$text))
  if (node$kind == "comment") return(sprintf(";; %s", node$text))
  if (node$kind == "list")
    return(sprintf("(%s)", paste(vapply(node$children, .dai_unparse_node, character(1)), collapse = " ")))
  stop("dai parse error: cannot unparse node kind '", node$kind, "'")
}

## -- date / wait-condition mini-language (inverse) -------------------------
## The inverse of render_condition()/render_wait_from_date() (dai_helpers.R).
## Shared by every field_operation whose `date` or `condition` field goes
## through that mini-language (fertilise/sow/harvest/cut/irrigate_until --
## see dai_management.R). Anything the mini-language doesn't have a
## shorthand for round-trips through `raw:`, its own documented escape
## hatch, rather than failing -- see this file's scope note at the top.

#' Inverse of `render_condition()`: given the single node representing a
#' rendered condition (always a parenthesized form), reconstruct the
#' `date`/`condition` spec that would render back to it.
#' @keywords internal
.dai_parse_condition <- function(node) {
  if (node$kind != "list" || length(node$children) < 1 || node$children[[1]]$kind != "atom")
    return(list(raw = .dai_unparse_node(node)))
  head <- node$children[[1]]$text
  ch <- node$children[-1]

  if (identical(head, "mm_dd") && length(ch) == 2)
    return(list(mm_dd = sprintf("%s-%s", ch[[1]]$text, ch[[2]]$text)))

  if (identical(head, "crop_ds_after") && length(ch) == 3 &&
      ch[[1]]$kind == "string" && ch[[2]]$kind == "atom" && ch[[3]]$kind == "bracket")
    return(list(ds = as.numeric(ch[[2]]$text), crop = ch[[1]]$text))

  if (identical(head, "crop_dm_over") && length(ch) >= 3 &&
      ch[[1]]$kind == "string" && ch[[2]]$kind == "atom" && ch[[3]]$kind == "bracket") {
    out <- list(crop = ch[[1]]$text, amount = as.numeric(ch[[2]]$text), unit = ch[[3]]$text)
    if (length(ch) >= 4 && ch[[4]]$kind == "list" && ch[[4]]$children[[1]]$text == "height") {
      hc <- ch[[4]]$children
      out$height <- as.numeric(hc[[2]]$text); out$unit_height <- hc[[3]]$text
    }
    return(list(crop_dm_over = out))
  }

  if (identical(head, "soil_water_pressure_above") && length(ch) == 2 &&
      ch[[1]]$children[[1]]$text == "height" && ch[[2]]$children[[1]]$text == "potential") {
    hc <- ch[[1]]$children; pc <- ch[[2]]$children
    return(list(soil_water_pressure_above = list(
      height = as.numeric(hc[[2]]$text), unit_height = hc[[3]]$text,
      potential = as.numeric(pc[[2]]$text), unit_potential = pc[[3]]$text)))
  }

  if (identical(head, "not") && length(ch) == 1)
    return(list(not = .dai_parse_condition(ch[[1]])))
  if (identical(head, "or") && length(ch) >= 1)
    return(list(any_of = lapply(ch, .dai_parse_condition)))
  if (identical(head, "and") && length(ch) >= 1)
    return(list(all_of = lapply(ch, .dai_parse_condition)))

  list(raw = .dai_unparse_node(node))
}

#' Inverse of `render_wait_from_date()`: given a node that might be a
#' `(wait_mm_dd ..)` / `(wait_days ..)` / `(wait COND)` form, reconstruct
#' the `date` spec it came from. Returns `NULL` if `node` isn't one of
#' these three shapes at all (the caller then knows this isn't a wait).
#' @keywords internal
.dai_parse_wait_form <- function(node) {
  if (node$kind != "list" || length(node$children) < 1 || node$children[[1]]$kind != "atom")
    return(NULL)
  head <- node$children[[1]]$text
  ch <- node$children[-1]
  if (identical(head, "wait_mm_dd") && length(ch) == 2)
    return(list(mm_dd = sprintf("%s-%s", ch[[1]]$text, ch[[2]]$text)))
  if (identical(head, "wait_days") && length(ch) == 1)
    return(list(days = as.numeric(ch[[1]]$text)))
  if (identical(head, "wait") && length(ch) == 1)
    return(.dai_parse_condition(ch[[1]]))
  NULL
}

## dai_parse_helpers.R ends here.
